on:
  pull_request: {}
  schedule:
    - cron: '0 0 * * 6'
concurrency:
  group: semgrep-${{ github.event_name }}-${{ github.head_ref || github.run_id }}
  cancel-in-progress: true
permissions:
  contents: read
jobs:
  semgrep:
    name: semgrep-oss
    runs-on: ubuntu-slim
    steps:
      - uses: actions/checkout@v5
      - run: pip install semgrep==1.157.0
      - run: semgrep scan --config=auto