on:
  pull_request: {}
  schedule:
    - cron: '0 0 * * 6'
name: Semgrep CE scan test
jobs:
  semgrep:
    name: semgrep-oss
    runs-on: ubuntu-latest
    container:
      image: semgrep/semgrep
    steps:
      - uses: actions/checkout@v5
      - run: semgrep scan --config=auto
